### ISSUE TITLE
Is it crazy to have a vcap_services / vcap_application parser in compile-extensions?

### ISSUE THREAD

**Issue by sks** [cloudfoundry-incubator/compile-extensions#9]
Hi Team,

Has anyone built a generic VCAP_SERVICES / VCAP_APPLICATION parser so that the buildpacks can extract credential informations from the environment without doing something more hacky?

I've been using something like this in [get_credentials](https://github.com/sks/staticfile-buildpack/blob/master/bin/get_credentials) and [get_env](https://github.com/sks/staticfile-buildpack/blob/master/bin/get_env).

Is there a better way to do this ?

Why am I doing this ?
1. Parse out application names with ease.
2. Parse out credentials from vcap_services , for eg: for newrelic license key from Services
3. check if the application is bound to a particular kind of services.

Any thoughts ?

**Comment by RochesterinNYC** [comment]
Hi @sks, thanks for the issue. How are you currently utilizing those `get_credentials` and `get_env` utilities? You've provided a succinct explanation of what they do, and we're interested in hearing more about how they are actually used within your buildpacks.

**Comment by flavorjones** [comment]
Possibly worth noting that I usually use `jq` to retrieve data from these
environment variables, rather than write specialty methods or scripts.

**Comment by sks** [comment]
@RochesterinNYC : I am using this at the moment to check if the application has `newrelic` binding and start the monitoring process accordingly.

And in `staticfile_buildpack` ,I use the `get_credentials` to fetch the  `credentials.url` and stick it in `nginx.conf`

**Comment by RochesterinNYC** [comment]
@sks We'd be open to a PR.
